// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gordon.NetParameter.proto

#ifndef PROTOBUF_gordon_2eNetParameter_2eproto__INCLUDED
#define PROTOBUF_gordon_2eNetParameter_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace gordon {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_gordon_2eNetParameter_2eproto();
void protobuf_AssignDesc_gordon_2eNetParameter_2eproto();
void protobuf_ShutdownFile_gordon_2eNetParameter_2eproto();

class LayerDictionary;
class LayerDictionary_ParamBlob;
class LayerDictionary_ParamBlob_ParamValue;
class NetParameter;

enum LayerDictionary_BlobType {
  LayerDictionary_BlobType_WEIGHT = 0,
  LayerDictionary_BlobType_BIAS = 1
};
bool LayerDictionary_BlobType_IsValid(int value);
const LayerDictionary_BlobType LayerDictionary_BlobType_BlobType_MIN = LayerDictionary_BlobType_WEIGHT;
const LayerDictionary_BlobType LayerDictionary_BlobType_BlobType_MAX = LayerDictionary_BlobType_BIAS;
const int LayerDictionary_BlobType_BlobType_ARRAYSIZE = LayerDictionary_BlobType_BlobType_MAX + 1;

const ::google::protobuf::EnumDescriptor* LayerDictionary_BlobType_descriptor();
inline const ::std::string& LayerDictionary_BlobType_Name(LayerDictionary_BlobType value) {
  return ::google::protobuf::internal::NameOfEnum(
    LayerDictionary_BlobType_descriptor(), value);
}
inline bool LayerDictionary_BlobType_Parse(
    const ::std::string& name, LayerDictionary_BlobType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<LayerDictionary_BlobType>(
    LayerDictionary_BlobType_descriptor(), name, value);
}
// ===================================================================

class LayerDictionary_ParamBlob_ParamValue : public ::google::protobuf::Message {
 public:
  LayerDictionary_ParamBlob_ParamValue();
  virtual ~LayerDictionary_ParamBlob_ParamValue();

  LayerDictionary_ParamBlob_ParamValue(const LayerDictionary_ParamBlob_ParamValue& from);

  inline LayerDictionary_ParamBlob_ParamValue& operator=(const LayerDictionary_ParamBlob_ParamValue& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LayerDictionary_ParamBlob_ParamValue& default_instance();

  void Swap(LayerDictionary_ParamBlob_ParamValue* other);

  // implements Message ----------------------------------------------

  LayerDictionary_ParamBlob_ParamValue* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LayerDictionary_ParamBlob_ParamValue& from);
  void MergeFrom(const LayerDictionary_ParamBlob_ParamValue& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double val = 1;
  inline bool has_val() const;
  inline void clear_val();
  static const int kValFieldNumber = 1;
  inline double val() const;
  inline void set_val(double value);

  // @@protoc_insertion_point(class_scope:gordon.LayerDictionary.ParamBlob.ParamValue)
 private:
  inline void set_has_val();
  inline void clear_has_val();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  double val_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_gordon_2eNetParameter_2eproto();
  friend void protobuf_AssignDesc_gordon_2eNetParameter_2eproto();
  friend void protobuf_ShutdownFile_gordon_2eNetParameter_2eproto();

  void InitAsDefaultInstance();
  static LayerDictionary_ParamBlob_ParamValue* default_instance_;
};
// -------------------------------------------------------------------

class LayerDictionary_ParamBlob : public ::google::protobuf::Message {
 public:
  LayerDictionary_ParamBlob();
  virtual ~LayerDictionary_ParamBlob();

  LayerDictionary_ParamBlob(const LayerDictionary_ParamBlob& from);

  inline LayerDictionary_ParamBlob& operator=(const LayerDictionary_ParamBlob& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LayerDictionary_ParamBlob& default_instance();

  void Swap(LayerDictionary_ParamBlob* other);

  // implements Message ----------------------------------------------

  LayerDictionary_ParamBlob* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LayerDictionary_ParamBlob& from);
  void MergeFrom(const LayerDictionary_ParamBlob& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef LayerDictionary_ParamBlob_ParamValue ParamValue;

  // accessors -------------------------------------------------------

  // required int32 cube_num = 1;
  inline bool has_cube_num() const;
  inline void clear_cube_num();
  static const int kCubeNumFieldNumber = 1;
  inline ::google::protobuf::int32 cube_num() const;
  inline void set_cube_num(::google::protobuf::int32 value);

  // required int32 cube_size = 2;
  inline bool has_cube_size() const;
  inline void clear_cube_size();
  static const int kCubeSizeFieldNumber = 2;
  inline ::google::protobuf::int32 cube_size() const;
  inline void set_cube_size(::google::protobuf::int32 value);

  // required int32 cube_ch = 3;
  inline bool has_cube_ch() const;
  inline void clear_cube_ch();
  static const int kCubeChFieldNumber = 3;
  inline ::google::protobuf::int32 cube_ch() const;
  inline void set_cube_ch(::google::protobuf::int32 value);

  // required string lname = 4;
  inline bool has_lname() const;
  inline void clear_lname();
  static const int kLnameFieldNumber = 4;
  inline const ::std::string& lname() const;
  inline void set_lname(const ::std::string& value);
  inline void set_lname(const char* value);
  inline void set_lname(const char* value, size_t size);
  inline ::std::string* mutable_lname();
  inline ::std::string* release_lname();
  inline void set_allocated_lname(::std::string* lname);

  // optional .gordon.LayerDictionary.BlobType type = 5 [default = WEIGHT];
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 5;
  inline ::gordon::LayerDictionary_BlobType type() const;
  inline void set_type(::gordon::LayerDictionary_BlobType value);

  // repeated .gordon.LayerDictionary.ParamBlob.ParamValue param_val = 6;
  inline int param_val_size() const;
  inline void clear_param_val();
  static const int kParamValFieldNumber = 6;
  inline const ::gordon::LayerDictionary_ParamBlob_ParamValue& param_val(int index) const;
  inline ::gordon::LayerDictionary_ParamBlob_ParamValue* mutable_param_val(int index);
  inline ::gordon::LayerDictionary_ParamBlob_ParamValue* add_param_val();
  inline const ::google::protobuf::RepeatedPtrField< ::gordon::LayerDictionary_ParamBlob_ParamValue >&
      param_val() const;
  inline ::google::protobuf::RepeatedPtrField< ::gordon::LayerDictionary_ParamBlob_ParamValue >*
      mutable_param_val();

  // @@protoc_insertion_point(class_scope:gordon.LayerDictionary.ParamBlob)
 private:
  inline void set_has_cube_num();
  inline void clear_has_cube_num();
  inline void set_has_cube_size();
  inline void clear_has_cube_size();
  inline void set_has_cube_ch();
  inline void clear_has_cube_ch();
  inline void set_has_lname();
  inline void clear_has_lname();
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 cube_num_;
  ::google::protobuf::int32 cube_size_;
  ::std::string* lname_;
  ::google::protobuf::int32 cube_ch_;
  int type_;
  ::google::protobuf::RepeatedPtrField< ::gordon::LayerDictionary_ParamBlob_ParamValue > param_val_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];

  friend void  protobuf_AddDesc_gordon_2eNetParameter_2eproto();
  friend void protobuf_AssignDesc_gordon_2eNetParameter_2eproto();
  friend void protobuf_ShutdownFile_gordon_2eNetParameter_2eproto();

  void InitAsDefaultInstance();
  static LayerDictionary_ParamBlob* default_instance_;
};
// -------------------------------------------------------------------

class LayerDictionary : public ::google::protobuf::Message {
 public:
  LayerDictionary();
  virtual ~LayerDictionary();

  LayerDictionary(const LayerDictionary& from);

  inline LayerDictionary& operator=(const LayerDictionary& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LayerDictionary& default_instance();

  void Swap(LayerDictionary* other);

  // implements Message ----------------------------------------------

  LayerDictionary* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LayerDictionary& from);
  void MergeFrom(const LayerDictionary& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef LayerDictionary_ParamBlob ParamBlob;

  typedef LayerDictionary_BlobType BlobType;
  static const BlobType WEIGHT = LayerDictionary_BlobType_WEIGHT;
  static const BlobType BIAS = LayerDictionary_BlobType_BIAS;
  static inline bool BlobType_IsValid(int value) {
    return LayerDictionary_BlobType_IsValid(value);
  }
  static const BlobType BlobType_MIN =
    LayerDictionary_BlobType_BlobType_MIN;
  static const BlobType BlobType_MAX =
    LayerDictionary_BlobType_BlobType_MAX;
  static const int BlobType_ARRAYSIZE =
    LayerDictionary_BlobType_BlobType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  BlobType_descriptor() {
    return LayerDictionary_BlobType_descriptor();
  }
  static inline const ::std::string& BlobType_Name(BlobType value) {
    return LayerDictionary_BlobType_Name(value);
  }
  static inline bool BlobType_Parse(const ::std::string& name,
      BlobType* value) {
    return LayerDictionary_BlobType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated .gordon.LayerDictionary.ParamBlob blobs = 1;
  inline int blobs_size() const;
  inline void clear_blobs();
  static const int kBlobsFieldNumber = 1;
  inline const ::gordon::LayerDictionary_ParamBlob& blobs(int index) const;
  inline ::gordon::LayerDictionary_ParamBlob* mutable_blobs(int index);
  inline ::gordon::LayerDictionary_ParamBlob* add_blobs();
  inline const ::google::protobuf::RepeatedPtrField< ::gordon::LayerDictionary_ParamBlob >&
      blobs() const;
  inline ::google::protobuf::RepeatedPtrField< ::gordon::LayerDictionary_ParamBlob >*
      mutable_blobs();

  // @@protoc_insertion_point(class_scope:gordon.LayerDictionary)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::gordon::LayerDictionary_ParamBlob > blobs_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_gordon_2eNetParameter_2eproto();
  friend void protobuf_AssignDesc_gordon_2eNetParameter_2eproto();
  friend void protobuf_ShutdownFile_gordon_2eNetParameter_2eproto();

  void InitAsDefaultInstance();
  static LayerDictionary* default_instance_;
};
// -------------------------------------------------------------------

class NetParameter : public ::google::protobuf::Message {
 public:
  NetParameter();
  virtual ~NetParameter();

  NetParameter(const NetParameter& from);

  inline NetParameter& operator=(const NetParameter& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NetParameter& default_instance();

  void Swap(NetParameter* other);

  // implements Message ----------------------------------------------

  NetParameter* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const NetParameter& from);
  void MergeFrom(const NetParameter& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .gordon.LayerDictionary dict = 1;
  inline int dict_size() const;
  inline void clear_dict();
  static const int kDictFieldNumber = 1;
  inline const ::gordon::LayerDictionary& dict(int index) const;
  inline ::gordon::LayerDictionary* mutable_dict(int index);
  inline ::gordon::LayerDictionary* add_dict();
  inline const ::google::protobuf::RepeatedPtrField< ::gordon::LayerDictionary >&
      dict() const;
  inline ::google::protobuf::RepeatedPtrField< ::gordon::LayerDictionary >*
      mutable_dict();

  // @@protoc_insertion_point(class_scope:gordon.NetParameter)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::gordon::LayerDictionary > dict_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_gordon_2eNetParameter_2eproto();
  friend void protobuf_AssignDesc_gordon_2eNetParameter_2eproto();
  friend void protobuf_ShutdownFile_gordon_2eNetParameter_2eproto();

  void InitAsDefaultInstance();
  static NetParameter* default_instance_;
};
// ===================================================================


// ===================================================================

// LayerDictionary_ParamBlob_ParamValue

// required double val = 1;
inline bool LayerDictionary_ParamBlob_ParamValue::has_val() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LayerDictionary_ParamBlob_ParamValue::set_has_val() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LayerDictionary_ParamBlob_ParamValue::clear_has_val() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LayerDictionary_ParamBlob_ParamValue::clear_val() {
  val_ = 0;
  clear_has_val();
}
inline double LayerDictionary_ParamBlob_ParamValue::val() const {
  return val_;
}
inline void LayerDictionary_ParamBlob_ParamValue::set_val(double value) {
  set_has_val();
  val_ = value;
}

// -------------------------------------------------------------------

// LayerDictionary_ParamBlob

// required int32 cube_num = 1;
inline bool LayerDictionary_ParamBlob::has_cube_num() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LayerDictionary_ParamBlob::set_has_cube_num() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LayerDictionary_ParamBlob::clear_has_cube_num() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LayerDictionary_ParamBlob::clear_cube_num() {
  cube_num_ = 0;
  clear_has_cube_num();
}
inline ::google::protobuf::int32 LayerDictionary_ParamBlob::cube_num() const {
  return cube_num_;
}
inline void LayerDictionary_ParamBlob::set_cube_num(::google::protobuf::int32 value) {
  set_has_cube_num();
  cube_num_ = value;
}

// required int32 cube_size = 2;
inline bool LayerDictionary_ParamBlob::has_cube_size() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LayerDictionary_ParamBlob::set_has_cube_size() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LayerDictionary_ParamBlob::clear_has_cube_size() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LayerDictionary_ParamBlob::clear_cube_size() {
  cube_size_ = 0;
  clear_has_cube_size();
}
inline ::google::protobuf::int32 LayerDictionary_ParamBlob::cube_size() const {
  return cube_size_;
}
inline void LayerDictionary_ParamBlob::set_cube_size(::google::protobuf::int32 value) {
  set_has_cube_size();
  cube_size_ = value;
}

// required int32 cube_ch = 3;
inline bool LayerDictionary_ParamBlob::has_cube_ch() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void LayerDictionary_ParamBlob::set_has_cube_ch() {
  _has_bits_[0] |= 0x00000004u;
}
inline void LayerDictionary_ParamBlob::clear_has_cube_ch() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void LayerDictionary_ParamBlob::clear_cube_ch() {
  cube_ch_ = 0;
  clear_has_cube_ch();
}
inline ::google::protobuf::int32 LayerDictionary_ParamBlob::cube_ch() const {
  return cube_ch_;
}
inline void LayerDictionary_ParamBlob::set_cube_ch(::google::protobuf::int32 value) {
  set_has_cube_ch();
  cube_ch_ = value;
}

// required string lname = 4;
inline bool LayerDictionary_ParamBlob::has_lname() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void LayerDictionary_ParamBlob::set_has_lname() {
  _has_bits_[0] |= 0x00000008u;
}
inline void LayerDictionary_ParamBlob::clear_has_lname() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void LayerDictionary_ParamBlob::clear_lname() {
  if (lname_ != &::google::protobuf::internal::kEmptyString) {
    lname_->clear();
  }
  clear_has_lname();
}
inline const ::std::string& LayerDictionary_ParamBlob::lname() const {
  return *lname_;
}
inline void LayerDictionary_ParamBlob::set_lname(const ::std::string& value) {
  set_has_lname();
  if (lname_ == &::google::protobuf::internal::kEmptyString) {
    lname_ = new ::std::string;
  }
  lname_->assign(value);
}
inline void LayerDictionary_ParamBlob::set_lname(const char* value) {
  set_has_lname();
  if (lname_ == &::google::protobuf::internal::kEmptyString) {
    lname_ = new ::std::string;
  }
  lname_->assign(value);
}
inline void LayerDictionary_ParamBlob::set_lname(const char* value, size_t size) {
  set_has_lname();
  if (lname_ == &::google::protobuf::internal::kEmptyString) {
    lname_ = new ::std::string;
  }
  lname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* LayerDictionary_ParamBlob::mutable_lname() {
  set_has_lname();
  if (lname_ == &::google::protobuf::internal::kEmptyString) {
    lname_ = new ::std::string;
  }
  return lname_;
}
inline ::std::string* LayerDictionary_ParamBlob::release_lname() {
  clear_has_lname();
  if (lname_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = lname_;
    lname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void LayerDictionary_ParamBlob::set_allocated_lname(::std::string* lname) {
  if (lname_ != &::google::protobuf::internal::kEmptyString) {
    delete lname_;
  }
  if (lname) {
    set_has_lname();
    lname_ = lname;
  } else {
    clear_has_lname();
    lname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional .gordon.LayerDictionary.BlobType type = 5 [default = WEIGHT];
inline bool LayerDictionary_ParamBlob::has_type() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void LayerDictionary_ParamBlob::set_has_type() {
  _has_bits_[0] |= 0x00000010u;
}
inline void LayerDictionary_ParamBlob::clear_has_type() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void LayerDictionary_ParamBlob::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::gordon::LayerDictionary_BlobType LayerDictionary_ParamBlob::type() const {
  return static_cast< ::gordon::LayerDictionary_BlobType >(type_);
}
inline void LayerDictionary_ParamBlob::set_type(::gordon::LayerDictionary_BlobType value) {
  assert(::gordon::LayerDictionary_BlobType_IsValid(value));
  set_has_type();
  type_ = value;
}

// repeated .gordon.LayerDictionary.ParamBlob.ParamValue param_val = 6;
inline int LayerDictionary_ParamBlob::param_val_size() const {
  return param_val_.size();
}
inline void LayerDictionary_ParamBlob::clear_param_val() {
  param_val_.Clear();
}
inline const ::gordon::LayerDictionary_ParamBlob_ParamValue& LayerDictionary_ParamBlob::param_val(int index) const {
  return param_val_.Get(index);
}
inline ::gordon::LayerDictionary_ParamBlob_ParamValue* LayerDictionary_ParamBlob::mutable_param_val(int index) {
  return param_val_.Mutable(index);
}
inline ::gordon::LayerDictionary_ParamBlob_ParamValue* LayerDictionary_ParamBlob::add_param_val() {
  return param_val_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::gordon::LayerDictionary_ParamBlob_ParamValue >&
LayerDictionary_ParamBlob::param_val() const {
  return param_val_;
}
inline ::google::protobuf::RepeatedPtrField< ::gordon::LayerDictionary_ParamBlob_ParamValue >*
LayerDictionary_ParamBlob::mutable_param_val() {
  return &param_val_;
}

// -------------------------------------------------------------------

// LayerDictionary

// repeated .gordon.LayerDictionary.ParamBlob blobs = 1;
inline int LayerDictionary::blobs_size() const {
  return blobs_.size();
}
inline void LayerDictionary::clear_blobs() {
  blobs_.Clear();
}
inline const ::gordon::LayerDictionary_ParamBlob& LayerDictionary::blobs(int index) const {
  return blobs_.Get(index);
}
inline ::gordon::LayerDictionary_ParamBlob* LayerDictionary::mutable_blobs(int index) {
  return blobs_.Mutable(index);
}
inline ::gordon::LayerDictionary_ParamBlob* LayerDictionary::add_blobs() {
  return blobs_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::gordon::LayerDictionary_ParamBlob >&
LayerDictionary::blobs() const {
  return blobs_;
}
inline ::google::protobuf::RepeatedPtrField< ::gordon::LayerDictionary_ParamBlob >*
LayerDictionary::mutable_blobs() {
  return &blobs_;
}

// -------------------------------------------------------------------

// NetParameter

// repeated .gordon.LayerDictionary dict = 1;
inline int NetParameter::dict_size() const {
  return dict_.size();
}
inline void NetParameter::clear_dict() {
  dict_.Clear();
}
inline const ::gordon::LayerDictionary& NetParameter::dict(int index) const {
  return dict_.Get(index);
}
inline ::gordon::LayerDictionary* NetParameter::mutable_dict(int index) {
  return dict_.Mutable(index);
}
inline ::gordon::LayerDictionary* NetParameter::add_dict() {
  return dict_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::gordon::LayerDictionary >&
NetParameter::dict() const {
  return dict_;
}
inline ::google::protobuf::RepeatedPtrField< ::gordon::LayerDictionary >*
NetParameter::mutable_dict() {
  return &dict_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace gordon

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::gordon::LayerDictionary_BlobType>() {
  return ::gordon::LayerDictionary_BlobType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_gordon_2eNetParameter_2eproto__INCLUDED
